name: Create Artifact
description: Creates a file from a variable and uploads it to an artifact.
author: DREST LTD
inputs:
  name:
    description: The name of the artifact to create.
    default: artifact
    required: false
  path:
    description: The path of the created file.
    required: true
  content:
    description: The contents of the created file.
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
